// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rgotzjhkzzeahruherxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJnb3R6amhrenplYWhydWhlcnhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMDk2ODcsImV4cCI6MjA2Nzg4NTY4N30.7T-Jg_0HO6d8JhDTftD368RC5ZlhbNZABS3X8X1s2VQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});